### ISSUE TITLE
Add operators for fmap and friends

### ISSUE THREAD

**Issue by bsima** [tfausak/flow#13]
Late-night haskell hacking has me thinking:

```haskell
> :t ($)
($) :: (a -> b) -> a -> b
> :t (<|)
(<|) :: (a -> b) -> a -> b
> :t (<$>)
(<$>) :: Functor f => (a -> b) -> f a -> f b
> :t fmap
fmap :: Functor f => (a -> b) -> f a -> f b
> let (<<|) = fmap
> :t (<<|)
(<<|) :: Functor f => (a -> b) -> f a -> f b
```

My proposal is to add functions `(<<|)` and `(|>>)` which do the equivalent of `(<|)` and `(|>)` but over functors.

So the example [here](https://en.wikibooks.org/wiki/Haskell/Applicative_functors#Application_in_functors) would go from:

```haskell
(+) <$> Just 3 <*> Just 4
```

to:

```haskell
(+) <<| Just 3 <*> Just 4
```

which IMHO shows the structure of the operation much better than the original. (Disclaimer: Haskell novice here, may have gotten some terminology wrong.)

**Comment by bsima** [comment]
```haskell
> :t flip fmap
flip fmap :: Functor f => f a -> (a -> b) -> f b
> :t (|>)
(|>) :: a -> (a -> b) -> b
```

so I think `(|>>) = flip fmap` should work...

**Comment by tfausak** [comment]
Thanks for the suggestion! I've stuck with "plain" functions for now because it's not clear to stop. If `(<$>)` is `(<<|)` in Flow, what would `(=<<)` be, `(<<<|)`? 

``` hs
($)   ::              (a ->   b) ->   a ->   b
(<$>) :: Functor f => (a ->   b) -> f a -> f b
(=<<) :: Monad m   => (a -> m b) -> m a -> m b
```

Furthermore I generally avoid the applicative style and prefer `do` notation. [`ApplicativeDo`](https://ghc.haskell.org/trac/ghc/wiki/ApplicativeDo) makes this especially nice. I would write your example as:

``` hs
do
  x <- Just 3
  y <- Just 4
  pure <| x + y -- or `pure (x + y)` or `pure $ x + y`
```

**Comment by tfausak** [comment]
I don't think I'll implement higher-order operators in Flow. If that's something you want, take a look at [`Data.Functor.Monadic`](https://hackage.haskell.org/package/functor-monadic-0.1.0.3/docs/Data-Functor-Monadic.html).

**Comment by infinity0** [comment]
FunctorMonadic wasn't as nice as I wanted it to be so I've gone ahead and uploaded https://hackage.haskell.org/package/op-0.1.0.0/docs/Control-Op.html
