### ISSUE TITLE
Flow operators for `Functor` and `Applicative`

### ISSUE THREAD

**Issue by vanceism7** [tfausak/flow#24]
I was working through this lib and realized, it might be nice to have some directional operators for functor and applicative as well.

Having the `<$>` pop up really uglies up the code flow.

Maybe something like 
`<$|` for `fmap` 
`|$>` for `flip fmap`. 
`<*|` for `apply` (I think thats the name of `<*>`)
`|*>` for `flip apply`?

Just spit balling here, but I think those would be some nice additions to make the lib a slight bit more complete. Luckily Monad already has nice directional operators. 

Thanks!

**Comment by vanceism7** [comment]
OH blah, sorry! Just saw https://github.com/tfausak/flow/issues/13. I should've looked harder before making an issue. Ill just go ahead and close this...

**Comment by tfausak** [comment]
No problem at all! I'm glad you found that earlier issue. 

Since Flow doesn't have these operators, I think you can get them from either [functor-monadic](https://hackage.haskell.org/package/functor-monadic-0.1.0.3) or [op](https://hackage.haskell.org/package/op-0.4.0.0).
