### ISSUE TITLE
Flow as a ghc proposal?

### ISSUE THREAD

**Issue by biuld** [tfausak/flow#25]
Hello, Taylor. Just came across this repo by accident and I like the idea of avoiding the problem of `Haskell are forced to read lines forwards and backwards at the same time`. Then I thought why not propose it as a ghc proposal? So Taylor are you interested? 😊

**Comment by tfausak** [comment]
It's already been proposed and rejected: https://github.com/haskell/core-libraries-committee/issues/78

**Comment by biuld** [comment]
Fine.🤷
