### ISSUE TITLE
Flow (from hackage targball) test suite failure

### ISSUE THREAD

**Issue by DanBurton** [tfausak/flow#9]
* `stack unpack flow-1.0.4`
* `stack test`

```
flow-1.0.4: test (suite: flow-test-suite)


<no location info>: can't find file: Flow.hs

Test suite failure for package flow-1.0.4
    flow-test-suite:  exited with: ExitFailure 1
Logs printed to console
```

**Comment by tfausak** [comment]
Weird. hpack didn't expose `Flow`. I explicitly added it in d42e65fcf9fcbab6cfbd2907f16f4da85f1f8b26, which should fix this.

**Comment by tfausak** [comment]
[Flow v1.0.5's tarball](http://hackage.haskell.org/package/flow-1.0.5/src/Flow.hs) includes `Flow.hs`, which was missing in v1.0.4. Can you confirm that the test suite works for you?

**Comment by DanBurton** [comment]
Works for me locally. I'll re-enable the test suite on stackage.
